### ISSUE TITLE
Resource types missing from ResourceTypeId

### ISSUE THREAD

**Issue by NealAJohnson** [labd/commercetools-python-sdk#141]
I'm trying to add a custom type for a `cart` which [is in the list of customizable data types](https://docs.commercetools.com/api/projects/types#list-of-customizable-data-types) but the [list of types in this project](https://github.com/labd/commercetools-python-sdk/blob/main/src/commercetools/platform/models/type.py#L567) doesn't seem to include it.

**Comment by mvantellingen** [comment]
Hi @NealAJohnson, it's best to continue the conversation here i think.

I just regenerated the Python SDK but am running into some issues with the new API Raml specs. Will need to fix this in https://github.com/commercetools/rmf-codegen/tree/main/languages/python This might take some time

**Comment by NealAJohnson** [comment]
So the issue is with the commercetools code generator? If you can log an issue (or explain it a little more and I can do so) we can reach out to our CT contact and pressure them to get on this ASAP.

**Comment by NealAJohnson** [comment]
@mvantellingen Any further movement on this? Anything we can push on CommerceTools to do?

**Comment by NealAJohnson** [comment]
@mvantellingen Checking in again, anything that can be done about this?

**Comment by NealAJohnson** [comment]
Turns out the issue I logged isn't relevant, it just happened to uncover the fact that the python SDK can't be regenerated. After trying to use the API directly I realized that there is no cart resource ID because the key used to create the custom type is `order` instead.

**Comment by mvantellingen** [comment]
Should be fixed in latest release, see https://pypi.org/project/commercetools/

Let us know if that is not the case
