### ISSUE TITLE
Schema field String(many=True) doesn't validate data correctly

### ISSUE THREAD

**Issue by mikedebock** [labd/commercetools-python-sdk#17]
The ProjectSchema does contains these fields:

```
countries = marshmallow.fields.String(many=True)
currencies = marshmallow.fields.String(many=True)
languages = marshmallow.fields.String(many=True)
```

When initialising this schema with this data, there are validation errors raised:

`{"countries": ["AT", "NL", "CH", "BE", "GB", "DE", "IT", "LU", "ES"], "currencies": ["EUR", "GBP", "CHF"], "languages": ["en-GB", "de-DE", "fr-FR", "nl-BE", "nl-NL"] }`

`marshmallow.exceptions.ValidationError: {'currencies': ['Not a valid string.'], 'countries': ['Not a valid string.'], 'languages': ['Not a valid string.']}`

But it works when I change the fields in the schema like this.
```
countries = marshmallow.fields.List(marshmallow.fields.String())
currencies = marshmallow.fields.List(marshmallow.fields.String())
languages = marshmallow.fields.List(marshmallow.fields.String())
```

**Comment by mvantellingen** [comment]
Fixed
